    name: S25_Ultra_Worker_Farm

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Tools
        run: |
          pip install --upgrade pip
          pip install coincurve pyTelegramBotAPI requests base58

      - name: Run Sniper
        run: python bot.py
